"""Local development environment: generated secrets, service ports and child-process settings."""

from __future__ import annotations

import os
import shlex
from dataclasses import dataclass
from pathlib import Path

from crp_core.config import default_data_dir
from crp_core.local_secrets import generate_token, read_secret_file, write_secret_file
from crp_devtools.engines import OPENGREP, TRIVY, pmd_home
from crp_devtools.infra import LOOPBACK, PostgresCluster, TemporalDevServer
from crp_devtools.paths import DevPaths

DATABASE_NAME = "crp"


def _port(env: str, default: int) -> int:
    return int(os.environ.get(env, default))


@dataclass(frozen=True, slots=True)
class DevPorts:
    postgres: int = _port("CRP_DEV_PG_PORT", 55432)
    temporal: int = _port("CRP_DEV_TEMPORAL_PORT", 7233)
    temporal_ui: int = _port("CRP_DEV_TEMPORAL_UI_PORT", 8233)
    api: int = _port("CRP_DEV_API_PORT", 8710)
    web: int = _port("CRP_DEV_WEB_PORT", 5173)


def ensure_secrets(paths: DevPaths) -> list[str]:
    """Create missing local secrets (owner-only). Returns the names of files created."""
    created = []
    for path in (paths.token_file, paths.postgres_password_file):
        if write_secret_file(path, generate_token()):
            created.append(path.name)
    return created


def dev_postgres(paths: DevPaths, ports: DevPorts) -> PostgresCluster:
    return PostgresCluster(
        data_dir=paths.postgres_data,
        port=ports.postgres,
        password=read_secret_file(paths.postgres_password_file),
        log_file=paths.logs / "postgres.log",
    )


def dev_temporal(paths: DevPaths, ports: DevPorts) -> TemporalDevServer:
    return TemporalDevServer(
        port=ports.temporal,
        ui_port=ports.temporal_ui,
        db_file=paths.temporal_db,
        log_file=paths.logs / "temporal.log",
        pid_file=paths.run / "temporal.pid",
    )


def artifact_root() -> Path:
    override = os.environ.get("CRP_ARTIFACT_ROOT")
    return Path(override) if override else default_data_dir() / "artifacts"


def service_env(
    *,
    repo: Path,
    token_file: Path,
    database_url: str,
    temporal_address: str,
    api_port: int,
    web_origins: tuple[str, ...],
    artifacts: Path,
    work_root: Path | None = None,
    log_format: str = "text",
) -> dict[str, str]:
    """``CRP_*`` settings for API/worker/tool child processes."""
    engine_dir = repo / ".local" / "engines"
    engines = {
        "CRP_PMD_HOME": str(pmd_home(engine_dir)),
        "CRP_OPENGREP_HOME": str(engine_dir / f"opengrep-{OPENGREP.version}"),
        "CRP_TRIVY_HOME": str(engine_dir / f"trivy-{TRIVY.version}"),
        "CRP_TRIVY_CACHE_DIR": str(engine_dir / "trivy-cache"),
        "CRP_ESLINT_RUNNER_DIR": str(repo / "engines" / "eslint-runner"),
        "CRP_WORK_ROOT": str(work_root or artifacts.parent / "work"),
    }
    return engines | {
        "CRP_ENVIRONMENT": "local",
        "CRP_AUTH_MODE": "local_token",
        "CRP_API_HOST": LOOPBACK,
        "CRP_API_PORT": str(api_port),
        "CRP_ALLOWED_WEB_ORIGINS": ",".join(web_origins),
        "CRP_LOCAL_TOKEN_FILE": str(token_file),
        "CRP_DATABASE_URL": database_url,
        "CRP_TEMPORAL_ADDRESS": temporal_address,
        "CRP_ARTIFACT_ROOT": str(artifacts),
        "CRP_TRUSTED_DEV_ROOT": str(repo),
        "CRP_LOG_FORMAT": log_format,
        "CRP_DEMO_ENABLED": "true",  # loopback only: lets the UI's "Try the demo" work locally
    }


def dev_service_env(paths: DevPaths, ports: DevPorts) -> dict[str, str]:
    cluster = dev_postgres(paths, ports)
    return service_env(
        repo=paths.repo,
        token_file=paths.token_file,
        database_url=cluster.url(DATABASE_NAME),
        temporal_address=f"{LOOPBACK}:{ports.temporal}",
        api_port=ports.api,
        web_origins=(f"http://{LOOPBACK}:{ports.web}", f"http://localhost:{ports.web}"),
        artifacts=artifact_root(),
    )


def write_env_file(paths: DevPaths, env: dict[str, str]) -> None:
    """Write ``.local/dev.env`` (owner-only) for running services manually."""
    lines = [
        "# Generated by crp-dev; contains local secrets. Do not commit or share.",
        "# Usage: set -a; . .local/dev.env; set +a",
    ]
    lines += [f"{key}={shlex.quote(value)}" for key, value in sorted(env.items())]
    write_secret_file(paths.env_file, "\n".join(lines), overwrite=True)


def child_env(extra: dict[str, str]) -> dict[str, str]:
    """Inherit PATH/HOME etc. but drop any pre-existing CRP_* values that could conflict."""
    base = {k: v for k, v in os.environ.items() if not k.startswith("CRP_")}
    for key in ("CRP_PG_BIN_DIR", "CRP_TEMPORAL_CLI", "CRP_REPO_ROOT"):
        if key in os.environ:
            base[key] = os.environ[key]
    base.update(extra)
    return base
