"""Validated fixes (P05): fix proposals bound to a snapshot, finding and patch hash, and their
validation runs.

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-01 00:05:19.416676
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fix_proposals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("recipe_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("behaviour_note", sa.Text(), nullable=True),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("target_line", sa.Integer(), nullable=True),
        sa.Column("rebased_from", sa.Uuid(), nullable=True),
        sa.Column(
            "allowed_paths",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("base_sha256", sa.String(length=64), nullable=False),
        sa.Column("result_sha256", sa.String(length=64), nullable=False),
        sa.Column("patch_sha256", sa.String(length=64), nullable=False),
        sa.Column("patch", sa.Text(), nullable=False),
        sa.Column(
            "edits",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("changed_lines", sa.Integer(), nullable=False),
        sa.Column("edited", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("validations_used", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_validations", sa.Integer(), server_default="5", nullable=False),
        sa.Column("rejected_reason", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "base_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_fix_proposals_base_sha256_format")
        ),
        sa.CheckConstraint("kind IN ('recipe', 'ai')", name=op.f("ck_fix_proposals_kind_valid")),
        sa.CheckConstraint(
            "patch_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_fix_proposals_patch_sha256_format")
        ),
        sa.CheckConstraint(
            "result_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_fix_proposals_result_sha256_format")
        ),
        sa.CheckConstraint(
            "state IN ('PROPOSED', 'VALIDATING', 'VALIDATED', 'VALIDATION_FAILED', 'REJECTED')",
            name=op.f("ck_fix_proposals_state_valid"),
        ),
        sa.CheckConstraint(
            "validations_used >= 0 AND validations_used <= max_validations",
            name=op.f("ck_fix_proposals_validation_budget"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_fix_proposals_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.id"],
            name=op.f("fk_fix_proposals_finding_id_findings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "project_id", "snapshot_id"],
            ["snapshots.workspace_id", "snapshots.project_id", "snapshots.id"],
            name=op.f("fk_fix_proposals_workspace_id_project_id_snapshot_id_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fix_proposals")),
    )
    op.create_index(
        op.f("ix_fix_proposals_finding_id"), "fix_proposals", ["finding_id"], unique=False
    )
    op.create_index(
        "ix_fix_proposals_project_id_created_at",
        "fix_proposals",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "fix_validations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("proposal_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("patch_sha256", sa.String(length=64), nullable=False),
        sa.Column("result_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "steps",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("requested_by", sa.Uuid(), nullable=True),
        sa.Column("workflow_id", sa.String(length=128), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('QUEUED', 'RUNNING', 'PASSED', 'FAILED', 'CANCELED')",
            name=op.f("ck_fix_validations_state_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["fix_proposals.id"],
            name=op.f("fk_fix_validations_proposal_id_fix_proposals"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
            name=op.f("fk_fix_validations_requested_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fix_validations")),
    )
    op.create_index(
        op.f("ix_fix_validations_proposal_id"), "fix_validations", ["proposal_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fix_validations_proposal_id"), table_name="fix_validations")
    op.drop_table("fix_validations")
    op.drop_index("ix_fix_proposals_project_id_created_at", table_name="fix_proposals")
    op.drop_index(op.f("ix_fix_proposals_finding_id"), table_name="fix_proposals")
    op.drop_table("fix_proposals")
    # ### end Alembic commands ###
