"""GitHub (P06): installations, repositories, project connections with review/publication
policy, webhook deliveries, link requests, code reviews, fix pull requests, commit metadata on
snapshots and the ``github`` source mode.

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-01 01:33:48.594852
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_MODES_BEFORE = "mode IN ('zip_upload', 'local_runner', 'browser_files', 'registered_mount')"
_MODES_AFTER = (
    "mode IN ('zip_upload', 'local_runner', 'browser_files', 'registered_mount', 'github')"
)
_TREE_SHA = "git_tree_sha IS NULL OR git_tree_sha ~ '^([0-9a-f]{40}|[0-9a-f]{64})$'"


def _modes(check: str) -> None:
    for table in ("sources", "intakes"):
        op.drop_constraint(op.f(f"ck_{table}_mode_valid"), table, type_="check")
        op.create_check_constraint(op.f(f"ck_{table}_mode_valid"), table, check)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "git_deliveries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("delivery_id", sa.String(length=64), nullable=False),
        sa.Column("event", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=True),
        sa.Column("installation_external_id", sa.BigInteger(), nullable=True),
        sa.Column("repository_external_id", sa.BigInteger(), nullable=True),
        sa.Column("outcome", sa.String(length=24), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column(
            "review_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("provider IN ('github')", name=op.f("ck_git_deliveries_provider_valid")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_git_deliveries")),
        sa.UniqueConstraint(
            "provider", "delivery_id", name=op.f("uq_git_deliveries_provider_delivery_id")
        ),
    )
    op.create_index(
        op.f("ix_git_deliveries_received_at"), "git_deliveries", ["received_at"], unique=False
    )
    op.create_table(
        "git_installations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("external_id", sa.BigInteger(), nullable=False),
        sa.Column("account_login", sa.String(length=255), nullable=False),
        sa.Column("account_type", sa.String(length=32), nullable=False),
        sa.Column("repository_selection", sa.String(length=16), nullable=True),
        sa.Column(
            "permissions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("suspended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("linked_by", sa.Uuid(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "provider IN ('github')", name=op.f("ck_git_installations_provider_valid")
        ),
        sa.ForeignKeyConstraint(
            ["linked_by"],
            ["users.id"],
            name=op.f("fk_git_installations_linked_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_git_installations_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_git_installations")),
        sa.UniqueConstraint(
            "provider", "external_id", name=op.f("uq_git_installations_provider_external_id")
        ),
        sa.UniqueConstraint(
            "workspace_id", "id", name=op.f("uq_git_installations_workspace_id_id")
        ),
    )
    op.create_index(
        op.f("ix_git_installations_workspace_id"),
        "git_installations",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "git_link_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("state_sha256", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_git_link_requests_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_git_link_requests_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_git_link_requests")),
        sa.UniqueConstraint("state_sha256", name=op.f("uq_git_link_requests_state_sha256")),
    )
    op.create_table(
        "git_connection_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column(
            "changes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_git_connection_events_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_git_connection_events_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_git_connection_events")),
    )
    op.create_index(
        op.f("ix_git_connection_events_project_id"),
        "git_connection_events",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "git_repositories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("installation_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.BigInteger(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("default_branch", sa.String(length=255), nullable=False),
        sa.Column("private", sa.Boolean(), nullable=False),
        sa.Column("archived", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "installation_id"],
            ["git_installations.workspace_id", "git_installations.id"],
            name=op.f("fk_git_repositories_workspace_id_installation_id_git_installations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_git_repositories")),
        sa.UniqueConstraint(
            "installation_id",
            "external_id",
            name=op.f("uq_git_repositories_installation_id_external_id"),
        ),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_git_repositories_workspace_id_id")),
    )
    op.create_index(
        op.f("ix_git_repositories_external_id"), "git_repositories", ["external_id"], unique=False
    )
    op.create_index(
        op.f("ix_git_repositories_installation_id"),
        "git_repositories",
        ["installation_id"],
        unique=False,
    )
    op.create_table(
        "git_connections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("review_pushes", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("review_pull_requests", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("review_forks", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("publish_checks", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("publish_pull_requests", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "check_fail_threshold", sa.String(length=16), server_default="never", nullable=False
        ),
        sa.Column("reconcile_days", sa.Integer(), server_default="7", nullable=False),
        sa.Column("last_full_review_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "check_fail_threshold IN ('never', 'critical', 'high', 'medium')",
            name=op.f("ck_git_connections_threshold_valid"),
        ),
        sa.CheckConstraint(
            "reconcile_days BETWEEN 1 AND 90", name=op.f("ck_git_connections_reconcile_days_range")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_git_connections_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_git_connections_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "project_id", "source_id"],
            ["sources.workspace_id", "sources.project_id", "sources.id"],
            name=op.f("fk_git_connections_workspace_id_project_id_source_id_sources"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "project_id"],
            ["projects.workspace_id", "projects.id"],
            name=op.f("fk_git_connections_workspace_id_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "repository_id"],
            ["git_repositories.workspace_id", "git_repositories.id"],
            name=op.f("fk_git_connections_workspace_id_repository_id_git_repositories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_git_connections")),
        sa.UniqueConstraint("project_id", name=op.f("uq_git_connections_project_id")),
        sa.UniqueConstraint("repository_id", name=op.f("uq_git_connections_repository_id")),
    )
    op.create_table(
        "code_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("ref", sa.String(length=255), nullable=True),
        sa.Column("head_sha", sa.String(length=64), nullable=True),
        sa.Column("pr_number", sa.Integer(), nullable=True),
        sa.Column("pr_title", sa.String(length=300), nullable=True),
        sa.Column("pr_author", sa.String(length=100), nullable=True),
        sa.Column("pr_url", sa.String(length=500), nullable=True),
        sa.Column("fork", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("base_ref", sa.String(length=255), nullable=True),
        sa.Column("base_sha", sa.String(length=64), nullable=True),
        sa.Column("merge_base_sha", sa.String(length=64), nullable=True),
        sa.Column("full", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("head_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("base_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("head_scan_id", sa.Uuid(), nullable=True),
        sa.Column("base_scan_id", sa.Uuid(), nullable=True),
        sa.Column(
            "changes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("publish_state", sa.String(length=16), nullable=True),
        sa.Column("publish_error", sa.Text(), nullable=True),
        sa.Column("check_run_id", sa.BigInteger(), nullable=True),
        sa.Column("comment_id", sa.BigInteger(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_by", sa.Uuid(), nullable=True),
        sa.Column("delivery_id", sa.String(length=64), nullable=True),
        sa.Column("requested_by", sa.Uuid(), nullable=True),
        sa.Column("workflow_id", sa.String(length=128), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "base_sha IS NULL OR base_sha ~ '^([0-9a-f]{40}|[0-9a-f]{64})$'",
            name=op.f("ck_code_reviews_base_sha_format"),
        ),
        sa.CheckConstraint(
            "head_sha IS NULL OR head_sha ~ '^([0-9a-f]{40}|[0-9a-f]{64})$'",
            name=op.f("ck_code_reviews_head_sha_format"),
        ),
        sa.CheckConstraint(
            "kind <> 'pull_request' OR pr_number IS NOT NULL",
            name=op.f("ck_code_reviews_pull_request_number"),
        ),
        sa.CheckConstraint(
            "kind IN ('branch', 'pull_request')", name=op.f("ck_code_reviews_kind_valid")
        ),
        sa.CheckConstraint(
            "merge_base_sha IS NULL OR merge_base_sha ~ '^([0-9a-f]{40}|[0-9a-f]{64})$'",
            name=op.f("ck_code_reviews_merge_base_sha_format"),
        ),
        sa.CheckConstraint(
            "publish_state IS NULL OR publish_state IN ('off', 'published', 'failed', 'skipped')",
            name=op.f("ck_code_reviews_publish_state_valid"),
        ),
        sa.CheckConstraint(
            "state IN ('QUEUED', 'CAPTURING', 'SCANNING', 'PUBLISHING', 'SUCCEEDED', 'PARTIAL', 'FAILED', 'SUPERSEDED', 'SKIPPED', 'CANCELED')",
            name=op.f("ck_code_reviews_state_valid"),
        ),
        sa.CheckConstraint(
            "trigger IN ('push', 'pull_request', 'manual', 'reconcile')",
            name=op.f("ck_code_reviews_trigger_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["base_scan_id"],
            ["scans.id"],
            name=op.f("fk_code_reviews_base_scan_id_scans"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["base_snapshot_id"],
            ["snapshots.id"],
            name=op.f("fk_code_reviews_base_snapshot_id_snapshots"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["git_connections.id"],
            name=op.f("fk_code_reviews_connection_id_git_connections"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["head_scan_id"],
            ["scans.id"],
            name=op.f("fk_code_reviews_head_scan_id_scans"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["head_snapshot_id"],
            ["snapshots.id"],
            name=op.f("fk_code_reviews_head_snapshot_id_snapshots"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
            name=op.f("fk_code_reviews_requested_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "project_id"],
            ["projects.workspace_id", "projects.id"],
            name=op.f("fk_code_reviews_workspace_id_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_code_reviews")),
        sa.UniqueConstraint(
            "project_id", "idempotency_key", name=op.f("uq_code_reviews_project_id_idempotency_key")
        ),
    )
    op.create_index(
        op.f("ix_code_reviews_head_scan_id"), "code_reviews", ["head_scan_id"], unique=False
    )
    op.create_index(
        "ix_code_reviews_project_id_created_at",
        "code_reviews",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "fix_pull_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("proposal_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("repository", sa.String(length=255), nullable=False),
        sa.Column("branch", sa.String(length=255), nullable=False),
        sa.Column("base_ref", sa.String(length=255), nullable=False),
        sa.Column("base_sha", sa.String(length=64), nullable=False),
        sa.Column("commit_sha", sa.String(length=64), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "base_sha ~ '^([0-9a-f]{40}|[0-9a-f]{64})$'",
            name=op.f("ck_fix_pull_requests_base_sha_format"),
        ),
        sa.CheckConstraint(
            "commit_sha ~ '^([0-9a-f]{40}|[0-9a-f]{64})$'",
            name=op.f("ck_fix_pull_requests_commit_sha_format"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_fix_pull_requests_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["fix_proposals.id"],
            name=op.f("fk_fix_pull_requests_proposal_id_fix_proposals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fix_pull_requests")),
        sa.UniqueConstraint("proposal_id", name=op.f("uq_fix_pull_requests_proposal_id")),
    )
    op.create_index(
        op.f("ix_fix_pull_requests_project_id"), "fix_pull_requests", ["project_id"], unique=False
    )
    op.add_column("snapshots", sa.Column("git_provider", sa.String(length=16), nullable=True))
    op.add_column("snapshots", sa.Column("git_repository", sa.String(length=255), nullable=True))
    op.add_column("snapshots", sa.Column("git_tree_sha", sa.String(length=64), nullable=True))
    op.add_column(
        "snapshots",
        sa.Column(
            "git_capture",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
    )
    op.create_index(
        "ix_snapshots_project_id_git_commit",
        "snapshots",
        ["project_id", "git_commit"],
        unique=False,
    )
    op.create_check_constraint(op.f("ck_snapshots_git_tree_sha_format"), "snapshots", _TREE_SHA)
    _modes(_MODES_AFTER)
    # ### end Alembic commands ###


def downgrade() -> None:
    # GitHub sources, their intakes and snapshots (and everything below them) are removed.
    op.execute("DELETE FROM sources WHERE mode = 'github'")
    op.execute("DELETE FROM intakes WHERE mode = 'github'")
    _modes(_MODES_BEFORE)
    op.drop_constraint(op.f("ck_snapshots_git_tree_sha_format"), "snapshots", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_snapshots_project_id_git_commit", table_name="snapshots")
    op.drop_column("snapshots", "git_capture")
    op.drop_column("snapshots", "git_tree_sha")
    op.drop_column("snapshots", "git_repository")
    op.drop_column("snapshots", "git_provider")
    op.drop_index(op.f("ix_fix_pull_requests_project_id"), table_name="fix_pull_requests")
    op.drop_table("fix_pull_requests")
    op.drop_index("ix_code_reviews_project_id_created_at", table_name="code_reviews")
    op.drop_index(op.f("ix_code_reviews_head_scan_id"), table_name="code_reviews")
    op.drop_table("code_reviews")
    op.drop_table("git_connections")
    op.drop_index(op.f("ix_git_repositories_installation_id"), table_name="git_repositories")
    op.drop_index(op.f("ix_git_repositories_external_id"), table_name="git_repositories")
    op.drop_table("git_repositories")
    op.drop_index(op.f("ix_git_connection_events_project_id"), table_name="git_connection_events")
    op.drop_table("git_connection_events")
    op.drop_table("git_link_requests")
    op.drop_index(op.f("ix_git_installations_workspace_id"), table_name="git_installations")
    op.drop_table("git_installations")
    op.drop_index(op.f("ix_git_deliveries_received_at"), table_name="git_deliveries")
    op.drop_table("git_deliveries")
    # ### end Alembic commands ###
