"""Fix workspaces (P08): change sets with per-file revisions, provenance events and checks, and
snapshot markers for workspace-derived snapshots.

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-08 22:16:13.015462
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "change_sets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("base_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("base_scan_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_change_sets_content_sha256_format")
        ),
        sa.ForeignKeyConstraint(
            ["base_scan_id"],
            ["scans.id"],
            name=op.f("fk_change_sets_base_scan_id_scans"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_change_sets_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "project_id", "base_snapshot_id"],
            ["snapshots.workspace_id", "snapshots.project_id", "snapshots.id"],
            name=op.f("fk_change_sets_workspace_id_project_id_base_snapshot_id_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_sets")),
    )
    op.create_index(
        "ix_change_sets_project_id_created_at",
        "change_sets",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "change_set_checks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("change_set_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "files",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("scan_id", sa.Uuid(), nullable=True),
        sa.Column("base_scan_id", sa.Uuid(), nullable=True),
        sa.Column(
            "result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("requested_by", sa.Uuid(), nullable=True),
        sa.Column("workflow_id", sa.String(length=128), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED', 'CANCELED')",
            name=op.f("ck_change_set_checks_state_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["base_scan_id"],
            ["scans.id"],
            name=op.f("fk_change_set_checks_base_scan_id_scans"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["change_set_id"],
            ["change_sets.id"],
            name=op.f("fk_change_set_checks_change_set_id_change_sets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
            name=op.f("fk_change_set_checks_requested_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scans.id"],
            name=op.f("fk_change_set_checks_scan_id_scans"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["snapshots.id"],
            name=op.f("fk_change_set_checks_snapshot_id_snapshots"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_set_checks")),
    )
    op.create_index(
        op.f("ix_change_set_checks_change_set_id"),
        "change_set_checks",
        ["change_set_id"],
        unique=False,
    )
    op.create_table(
        "change_set_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("change_set_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("path", sa.Text(), nullable=True),
        sa.Column("action", sa.String(length=8), nullable=True),
        sa.Column(
            "finding_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("recipe_id", sa.String(length=64), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "flags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("content_sha256", sa.String(length=64), nullable=True),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('manual', 'recipe', 'ai', 'revert', 'export')",
            name=op.f("ck_change_set_events_source_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_change_set_events_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["change_set_id"],
            ["change_sets.id"],
            name=op.f("fk_change_set_events_change_set_id_change_sets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_set_events")),
    )
    op.create_index(
        op.f("ix_change_set_events_change_set_id"),
        "change_set_events",
        ["change_set_id"],
        unique=False,
    )
    op.create_table(
        "change_set_files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("change_set_id", sa.Uuid(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("action", sa.String(length=8), nullable=False),
        sa.Column("base_sha256", sa.String(length=64), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("line_count", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=32), nullable=True),
        sa.Column(
            "flags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "sources",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(action = 'add') = (base_sha256 IS NULL)",
            name=op.f("ck_change_set_files_add_has_no_base"),
        ),
        sa.CheckConstraint(
            "(action = 'delete') = (sha256 IS NULL)",
            name=op.f("ck_change_set_files_delete_has_no_content"),
        ),
        sa.CheckConstraint(
            "action IN ('modify', 'add', 'delete')", name=op.f("ck_change_set_files_action_valid")
        ),
        sa.ForeignKeyConstraint(
            ["change_set_id"],
            ["change_sets.id"],
            name=op.f("fk_change_set_files_change_set_id_change_sets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_change_set_files_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_set_files")),
        sa.UniqueConstraint(
            "change_set_id", "path", name=op.f("uq_change_set_files_change_set_id_path")
        ),
    )
    op.create_index(
        op.f("ix_change_set_files_change_set_id"),
        "change_set_files",
        ["change_set_id"],
        unique=False,
    )
    op.add_column("snapshots", sa.Column("derived_from", sa.Uuid(), nullable=True))
    op.add_column("snapshots", sa.Column("change_set_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_snapshots_change_set_id"), "snapshots", ["change_set_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Workspace-derived snapshots (and their scans) go with the workspaces.
    op.execute("DELETE FROM snapshots WHERE change_set_id IS NOT NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_snapshots_change_set_id"), table_name="snapshots")
    op.drop_column("snapshots", "change_set_id")
    op.drop_column("snapshots", "derived_from")
    op.drop_index(op.f("ix_change_set_files_change_set_id"), table_name="change_set_files")
    op.drop_table("change_set_files")
    op.drop_index(op.f("ix_change_set_events_change_set_id"), table_name="change_set_events")
    op.drop_table("change_set_events")
    op.drop_index(op.f("ix_change_set_checks_change_set_id"), table_name="change_set_checks")
    op.drop_table("change_set_checks")
    op.drop_index("ix_change_sets_project_id_created_at", table_name="change_sets")
    op.drop_table("change_sets")
    # ### end Alembic commands ###
