import { useId, useState, type SubmitEvent } from "react";

import { describeError } from "../api/client";
import { signIn } from "../api/endpoints";
import { Alert } from "../components/Common";
import { BrandMark, Icon } from "../components/Icon";

export function LoginPage({ onSignedIn }: { onSignedIn: () => void }) {
  const tokenId = useId();
  const hintId = useId();
  const [token, setToken] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  async function submit(event: SubmitEvent<HTMLFormElement>) {
    event.preventDefault();
    setBusy(true);
    setError(null);
    try {
      await signIn(token.trim());
      setToken("");
      onSignedIn();
    } catch (caught) {
      setError(describeError(caught));
    } finally {
      setBusy(false);
    }
  }

  return (
    <main className="login" aria-labelledby="login-title">
      <div className="card login-card">
        <div className="row">
          <BrandMark />
          <div>
            <h1 id="login-title" className="gradient-text" style={{ fontSize: "1.5rem" }}>
              Code Review Platform
            </h1>
            <p className="muted small" style={{ margin: 0 }}>
              Evidence-first code intelligence · local development
            </p>
          </div>
        </div>
        <form
          onSubmit={(event) => {
            void submit(event);
          }}
        >
          <div className="field">
            <label htmlFor={tokenId}>Local API token</label>
            <input
              id={tokenId}
              name="token"
              type="password"
              autoComplete="off"
              required
              value={token}
              aria-describedby={hintId}
              onChange={(event) => {
                setToken(event.target.value);
              }}
            />
            <p id={hintId} className="hint">
              Generated by <code>make bootstrap</code>. Print it with{" "}
              <code>uv run crp-dev token --show</code>. It is exchanged for an HttpOnly session
              cookie and never stored by the browser.
            </p>
          </div>
          {error ? <Alert tone="bad">{error}</Alert> : null}
          <button type="submit" className="btn btn-primary" disabled={busy || token.trim() === ""}>
            <Icon name="shield" size={16} />
            {busy ? "Signing in…" : "Sign in"}
          </button>
        </form>
        <p className="hint">
          <Icon name="info" size={12} /> Loopback-only single-user mode. Hosted sign-in (SSO)
          arrives in Phase 7.
        </p>
      </div>
    </main>
  );
}
